project: 
  type: website
  output-dir: docs 

site-url: "https://blade-sp.github.io/PersonalWebsite/"

website:
  title: "Riccardo Spada"
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: CV
        href: cv.qmd
      - text: Resources
        href: resources.qmd
  page-footer:
    left: "© 2025 Riccardo Spada"
    right: "Made with [Quarto](https://quarto.org)"
    # Add a logo or image to the navbar:
    # logo: logo.png   
    # Add a custom favicon:
    # favicon: favicon.ico   

format:
  html:
    theme: flatly   
    css: styles.css  
    # toc: true table of contents for each page 
    # toc-depth: 2