---
title: "Decision making under ambiguity"
format: 
  html:
    toc: true
    toc-depth: 2
    number-sections: true
---

Ellsberg (1961) proposed a thought experiment that showed how people often prefer known risks over unknown risks, even when the expected outcomes are the same. This contradicts the predictions of standard expected utility theory.

The Ellsberg Paradox compare 2 events: a _risky_ event is known to occur with probability one half (known odds), whereas no information is given about the other, _ambiguous_, event (unknown odds). People prefer a bet on the risky event to a bet on the ambiguous event. 

>**Ellsberg Paradox**: People violate expected utility theory by avoiding ambiguous options.

According to Knight (1921), risks refer to situations where the probability distribution of the random variable is known, while uncertainties refer to situations where the probability distribution is not known or cannot be objectively determined. A further distinction can be made between uncertainty and ambiguity. Under uncertainty, decision makers are able to form a well-defined (subjective) probability distribution, while under ambiguity they do not (Harrison, 2011).

Unlike risk, where probabilities of different outcomes can be estimated from historical data, ambiguity arises when the probability distribution of outcomes is unknown (i.e. they are not available or decision-makers doesn't know them). People typically show **ambiguity aversion**, preferring known probabilities over unknown ones, even if the outcomes are mathematically equivalent. 

In this context decision models under ambiguity might be a better fit to explain farmers behaviour as they account for ambiguity aversion. Several models under ambiguity have been proposed, and are broadly divided into those that use second-order probabilities and those that do not (see also Ilut & Schneider (2022) for a review of applications of ambiguity models in macroeconomics and finance).


## Subjective Expected Utility

Let's use as a starting point Subjective Expected Utility (SEU) theory (Savage, 1954). Here the decision-maker attach _subjective probabilities_ to the various possible events. He/She thus **maximize Expected Utility** with respect to **a single subjective belief (probability distribution)**. Given $n$ possible events, the preference functional is given by:
$$
SEU = \sum^n_{i=1} p_i u_i
$$
where $p_i$ is the subjective probability that even $E_i$ occurs, so that $p_i = Prob(E_i)$ for all $i$, and $p_1 + p_2 + ... + p_n = 1$. 

SEU does not capture ambiguity because the decision-maker behaves **as if they know the probabilities** of all uncertain events, even if they’re "subjectively assigned".

## Multiple priors models

Several decision models have been proposed which extend SEU in order to allow a role for ambiguity in decision making. Most notable are the ‘‘maxmin expected utility with multiple priors’’ (MEU) model of Gilboa and Schmeidler (1989), which allows the agent’s beliefs to be represented by a set of probabilities, and the ‘‘Choquet expected utility’’ (CEU) model of Schmeidler (1989), which allows the agent’s beliefs to be represented by a unique but nonadditive probability.

### MinMax Expected Utility

The key innovation was to represent preferences using sets of beliefs $\mathcal{P}$ (multiple priors). Ambiguity can then be described by the size of this belief set. If this set of beliefs contain only on prior, the model reduces to the standard SEU. The MinMax EU model (Gilboa and Schmeidler, 1989) assumes that agents have multiple priors $p\in\mathcal{P}$ , and that they deal with ambiguity by acting as if they were using the most pessimistic belief of this set.

>Instead of a single known probability distribution, there is a **set of plausible distributions**. The decision-maker **maximizes utility under the worst-case distribution** from this set.

Basically, the agent pick the strategy that performs best in the worst-case scenario of expected utility.

Let $A$ a set of possible actions, $S$ a set of possible states of the world, and $u(a,s)$ the utility of action $a∈A$  in state $s∈S$. The decision-maker has a set of plausible probability distributions $(\mathcal{P})$ over $S$.  Then the agent chooses $a∗∈A$ such that:
$$
a∗=\arg\max_{a \in A} \left( \min_{P \in \mathcal{P}} \mathbb{E}_P[u(a, s)] \right)
$$
This model assumes that the decision-maker is extremely averse to ambiguity by always considering the worst case scenario.

### Alpha Expected Utility

The Alpha Expected Utility proposed by Ghirardato et al. (2004) is an generalization of the MinMax EU model that relax the assumption that decision-makers are extremely averse to ambiguity. 

Considering an ambiguous context in which the farmer only knows that the probability of a loss $(p)$ lies in a certain interval $P \in [p_{min},p_{max}]$, risk and ambiguity preferences are represented with the AEU model as:
$$
\max EU = \alpha E_{p_{max}}U(x) + (1 - \alpha)E_{p_{min}}U(x)
$$
Where $\alpha \in [1,0]$ is the decision-maker ambiguity attitude. 

Ambiguity $a$ is defined as the diameter of the interval $P$, $a=p_{max}-p_{min}$. The maximisation problem can be rewritten as: 
$$
maxEU = [\bar p - a(1/2-\alpha)]U(x) + [1-\bar p + a(1/2 - \alpha)]U(x)
$$
where $\bar p = (p_{min} + p_{max})/2$ is the mean probability of incurring the loss calculated as the center of the interval $P$.


__________________________________________________________________________

