---
title: "The publication process at economics field journal"
format: 
  html:
    toc: true
    toc-depth: 2
---

## Find the right journal 

Generally, two criteria: target audience/contribution you want to make, and journal impact factor. <br>

Decide which journals are a good fit for your research and laid down a list of target journals. Send the paper ~one tier above where you think it belongs. If you have no idea, look at your reference list and target the highest cited journal (a lot of journal like this to boost their impact factor). <br>

For agricultural economics see these sources:
* [A synthesis of journal rankings in Agricultural Economics and Environmental & Resource Economics](https://agrarpolitik-blog.com/2019/01/18/a-synthesis-of-journal-rankings-in-agricultural-economics-and-environmental-resource-economics/) - Bartosz Bartkowski, Nils Droste, Robert Finger
* [Journal Ranking in Agricultural Economics & Policy](https://agrarpolitik-blog.com/2017/06/04/journal-ranking-in-agricultural-economics-policy/) – Robert Finger 
* [Performance indicators for agricultural economic journals](https://weblog.wur.eu/economics/performance-indicators-for-agricultural-economic-journals/) - Robert Finger, Nils Droste, Bartosz Bartkowski and Frederic Ang

## Review and acceptance 

1. The journal editor will look at the paper and decide whether to send it out for review or “desk reject”. Editors are asking: Is this research interesting, novel, and important? Is this research likely of interest to readers of this journal? Does the paper appear competently communicated and competently executed? What you can do is to use the cover letter to explain why your paper is a good fit for that journal, by citing previous papers in that journal.
2. Desk reject decisions typically take between 1 day and 1 month. Do not bother arguing with desk rejections. Some perspective: Desk rejects are not bad outcomes….Be reflective, but not obsessive, after desk rejections.
3. If not desk rejected, the paper is under review. Wait! 2-5 months is now typical. You will eventually receive 1-4 referee reports (2-3 is most common) and a decision letter from the editor. The editor will most often be rejecting your paper. Almost all good journals have acceptance rates well below 10% (of a highly selected sample at the good journals). If you are lucky (and good), you will be invited to submit a revised manuscript addressing the editor and referee comments. The editor can accept, conditionally accept subject to minor changes, offer another ‘revise and resubmit,’ or reject after that. The whole process takes 0.5 years to several years at good journals. Over 1 year is the norm, not accounting for rejections.
4. A biggest reason for rejection is a minimal or unclear contribution (originality [gaps] and importance [why is the gap important]). Why is this question important? Why is your analysis new? Empirical contribution and Conceptual contribution (i.e. what you learn from data vs what other people in the field learn from your analysis). Usually is policy contribution but keep in mind that the readers are not policy-makers (use blogs/policy briefs for them). Another big reason for rejection is poor writing. Poorly written papers confuse the reviewer and obscure contributions. You must get the abstract and intro ‘right.’  Other common reasons for rejection include: Poor fit for the journal. Conclusions that do not follow from the analysis. Uncited references. Too many themes.

## Selected references and readings

Coming soon...